# Generated by Django 5.0.6 on 2025-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_alter_seance_options_remove_seance_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du contenu prévu', verbose_name='Description de la séance'),
        ),
        migrations.AddField(
            model_name='seance',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre de la séance'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='contenu_seance',
            field=models.TextField(blank=True, help_text='Décrivez le contenu réalisé pendant la séance', verbose_name='Cahier de texte'),
        ),
    ]
