# Generated by Django 5.0.6 on 2025-03-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_seance_description_seance_titre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='contenu_seance',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='titre',
        ),
    ]
