# Generated by Django 5.0.6 on 2025-03-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['titre'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterField(
            model_name='formation',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
